# Generated by Django 4.2.3 on 2023-12-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FluxEntrants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banque', models.CharField(max_length=200)),
                ('eferenceTransaction', models.CharField(max_length=200)),
                ('dateTransaction', models.DateField(auto_now_add=True)),
                ('typeSwfit', models.CharField(choices=[('MT103', 'MT103'), ('MT754', 'MT754')], default='MT103', max_length=30, null=True)),
                ('modeReglement', models.CharField(choices=[('TL', 'TL'), ('CD', 'CD'), ('RD', 'RD')], default='TL', max_length=3, null=True)),
                ('devise', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD')], default='EUR', max_length=5, null=True)),
                ('montantTransaction', models.FloatField(default=0.0, max_length=255)),
                ('tauxDeChange', models.FloatField(default=0.0, max_length=255)),
                ('nomDonneurOrdre', models.CharField(max_length=255)),
                ('nif_nni', models.CharField(max_length=200)),
                ('beneficiaire', models.CharField(max_length=100)),
                ('produit', models.CharField(max_length=200)),
                ('natureEconomique', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=200)),
            ],
        ),
    ]
